version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    user: "1001:1001" # Run as non-root user

  grafana:
    image: grafana/grafana
    env_file:
      - grafana.env # Contains GF_SECURITY_ADMIN_PASSWORD, GF_SECURITY_ADMIN_USER, etc.
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3006"
    networks:
      - monitoring
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"
    user: "104:107" # Run as non-root user
    depends_on:
      - prometheus
    
  your-service:
    build: ./your-service-directory
    ports:
      - "your-port-here:your-port-here"
    networks:
      - monitoring
    restart: on-failure
    environment:
      - SERVICE_ENV=production
      - ANOTHER_VAR=foobar
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    labels:
      org.label-schema.group: "application"

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-data:
    name: grafana_data
